n=-5:40
xn=(2).^-n.*Esc(0,n)
subplot(3,1,1)
stem(n,xn,'filled')
ylim([0 1])
title('$x[n]=2^{-n}u[n]$',Interpreter='latex')
xlabel('n'),ylabel('x[n]')
subplot(3,1,2)
hn=Esc(0,n)
stem(n,hn,'filled')
ylim([-1 2])
title('$h[n]=u[n]$',Interpreter='latex')
xlabel('n'),ylabel('h[n]')
subplot(3,1,3)
yn=conv_m(xn,n,hn,n)
stem(yn)